-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 17:16:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `webserver` ;

-- -----------------------------------------------------
-- Table `mydb`.`Edge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Edge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `a` VARCHAR(45) NULL,
  `v` FLOAT NULL,
  `b` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Heuristic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Heuristic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `a` VARCHAR(45) NULL,
  `b` VARCHAR(45) NULL,
  `v` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
